const ADD_DISH = 'ADD_DISH'
const DELETE_DISH = 'DELETE_DISH'
const DELETE_THIS_TYPE_DISH = 'DELETE_THIS_TYPE_DISH'
const DELETE_ALL_DISH = 'DELETE_ALL_DISH'

export const DISH_TYPES = {
  ADD_DISH,
  DELETE_DISH,
  DELETE_THIS_TYPE_DISH,
  DELETE_ALL_DISH
}
